### ISSUE TITLE
[RFE] refactor the pod controller as level driven

### ISSUE THREAD

**Issue by maiqueb** [k8snetworkplumbingwg/multus-dynamic-networks-controller#48]
**Is your feature request related to a problem? Please describe.**
Currently, if the user edits the pod's network-selection-elements and it fails to apply the new configuration,
it will retry up to 2 times (hard-coded), and if those fail, that's pretty much it. 

Never the less, the network-selection-elements for the pod are already updated, and follow-up attempts to plug
a new interface into the pod will be confusing, since for all the controller knows, the interface whose hotplug was
previously attempted succeeded.

This is bad.

**Describe the solution you'd like**
The controller should be level driven: we should compute the differences of the "desired state" - i.e. the network-selection-elements - and the current state - the network status annotations on the pod.

For every retry operation, we should check which interfaces present in the desired state are not reflected in the current state, and attempt to apply those.

**Additional context**
This feature / RFE consists hardening of the controller - i.e. it makes it more resilient. 

It is **not** a part of the MVP.

**Comment by maiqueb** [comment]
We should also evaluate if we want to have a separate annotation for the dynamic interfaces, instead of using the k8snetworkplumberswg `network-status`. This would have a clear separation of "who owns what".

This should be raised with the wg, to get feedback from it.

**Comment by kmabda** [comment]
Yes, making the controller drive a pod's network-selection-elements to a desired state based on the current one would be I think a better approach.

I think the network-status is still useful since it reflects the current state of what is currently plugged/configured in the pod, however what's missing is a history of what happened in time w.r.t. hotplug events; that might deserve a separate annotation, the pattern could be similar to a Pod's status.conditions.
